trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - script: echo Hello World from Job1 !!
    displayName: 'Running script from Job1'

- job: Job2
  steps:
  - script: |
      echo Hello World from Job2 !!
      echo This is multi-line script !!
    displayName: 'Multi-line Script'